# This workflow will do a clean installation of Node dependencies, cache/restore them, build the
# source code and run tests with the specified version of Node.
#
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI with Yarn v1

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-nodejs
      # https://docs.github.com/actions/using-workflows/caching-dependencies-to-speed-up-workflows
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: superbench.sh
        run: |
          wget https://git.io/superbench.sh
          sudo bash superbench.sh -- io

      - run: yarn --frozen-lockfile --prefer-offline
      - run: yarn lint
      - run: yarn make

      # https://docs.github.com/actions/using-workflows/storing-workflow-data-as-artifacts
      # https://github.com/actions/upload-artifact
      #
      # It's currently not possible to preview files in the artifact.
      # Follow up with https://github.com/actions/upload-artifact/issues/14 for further updates.
      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: coverage
